volumes:
  sonar_postgres_data: {}
  sonar_postgres_data_backups: {}
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:

services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonar-postgres/sonarqube
      - SONAR_JDBC_USERNAME=sonarqube
      - SONAR_JDBC_PASSWORD=sonarqube
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    depends_on:
      - sonar-db
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
  sonar-db:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    image: sonar-postgres
    container_name: sonar-postgres
    volumes:
      - sonar_postgres_data:/var/lib/postgresql/data
      - sonar_postgres_data_backups:/backups
    environment:
      POSTGRES_USER: sonarqube
      POSTGRES_PASSWORD: sonarqube
      POSTGRES_DB: sonarqube

  sonar-scanner:
    image: sonarsource/sonar-scanner-cli
    volumes:
      - ./:/usr/src
    environment:
      - SONAR_HOST_URL=http://sonarqube:9000
      - SONAR_TOKEN
