volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  production_django_media: {}


services:
  django:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    image: lea-django
    container_name: lea-django
    volumes:
      - production_django_media:/app/root/media
    depends_on:
      - postgres
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start


  postgres:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    image: lea-postgres
    container_name: lea-postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  traefik:
    build:
      context: .
      dockerfile: ./docker/traefik/Dockerfile
    image: lea-traefik
    container_name: lea-traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    image: lea-nginx
    container_name: lea-nginx
    depends_on:
      - django
    volumes:
      - production_django_media:/usr/share/nginx/media:ro
